version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
before_build:
- ps: >-
    cd src

    dotnet restore
build_script:
- ps: msbuild /nologo /m /t:build,pack
test_script:
- cmd: >-
    cd ..

    SET testdir=bin\Tests\%configuration%\net451\

    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe"
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"%testdir%Microsoft.VisualStudio.Composition.Tests.dll -noshadow -parallel all -html %testdir%testresults.html -xml %testdir%testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Microsoft.VisualStudio.Composition]*"
    -hideskipped:All
    -output:%testdir%code_coverage.xml

    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    codecov -f "%testdir%code_coverage.xml"
artifacts:
- path: bin\%configuration%\Packages\Microsoft.VisualStudio.Composition.15.*.nupkg
  name: NuGet Package
- path: bin\%configuration%\Packages\Microsoft.VisualStudio.Composition.AppHost.15.*.nupkg
  name: NuGet Package
