language: csharp
mono: none
dotnet: 2.1.4
mono: 5.10.0

branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/

os:
  - linux
  - osx

git:
  depth: false

install:
- nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
- msbuild src/Microsoft.VisualStudio.Composition.sln /nologo /m /v:quiet /t:restore

script:
- msbuild src/Microsoft.VisualStudio.Composition.sln /nologo /m /v:quiet /t:build
- mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe bin/Tests/Debug/net452/Microsoft.VisualStudio.Composition.Tests.dll
- dotnet test -f netcoreapp2.0 --no-build --no-restore src/tests/Microsoft.VisualStudio.Composition.Tests/
