trigger:
  branches:
    include: ["master", "v15.8"]
  paths:
    exclude: ["doc", "*.md"]

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
- job: Windows
  pool: VSEng-MicroBuildVS2017
  steps:
  - template: build.yml
